using Exam2.Backend.Entities;
using Microsoft.EntityFrameworkCore;
namespace Exam2.Backend.Data;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
    }

    public DbSet<Product> Products { get; set; }
    public DbSet<ProductDetail> ProductDetails { get; set; }
    public DbSet<Category> Categories { get; set; }
    public DbSet<User> Users { get; set; }
    public DbSet<Order> Orders { get; set; }
    public DbSet<OrderItem> OrderItems { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        
        // Product -> Details 
        modelBuilder.Entity<ProductDetail>()
            .HasOne(pd => pd.Product)
            .WithMany(p => p.Details)
            .HasForeignKey(pd => pd.ProductId)
            .OnDelete(DeleteBehavior.Cascade);
            
        // Order -> OrderItem 
        modelBuilder.Entity<OrderItem>()
            .HasOne(oi => oi.Order)
            .WithMany(o => o.Items)
            .HasForeignKey(oi => oi.OrderId)
            .OnDelete(DeleteBehavior.Cascade);

        // Seed Categories
        modelBuilder.Entity<Category>().HasData(
            new Category { Id = 1, Name = "Смартфони", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/categories/smartphones.jpg" },
            new Category { Id = 2, Name = "Ноутбуки", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/categories/laptops.jpg" },
            new Category { Id = 3, Name = "Клавіатури та мишки", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/categories/peripherals.jpg" },
            new Category { Id = 4, Name = "Навушники та аудіо", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/categories/audio.jpg" },
            new Category { Id = 5, Name = "Комплектуючі", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/categories/components.jpg" }
        );

        // Seed Users
        modelBuilder.Entity<User>().HasData(
            new User { Id = 1, Email = "admin@example.com", PasswordHash = "admin123", Role = "Admin", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/users/admin.jpg" },
            new User { Id = 2, Email = "test@example.com", PasswordHash = "test123", Role = "User", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/users/test-user.jpg" },
            new User { Id = 3, Email = "client@example.com", PasswordHash = "client123", Role = "User", ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/users/client-user.jpg" }
        );

        // Seed Products
        modelBuilder.Entity<Product>().HasData(
            new Product { Id = 1, CategoryId = 1, Name = "iPhone 15 Pro 128GB", Description = "Titanium Black =", Price = 49999m, OldPrice = 54999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/1.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 2, CategoryId = 1, Name = "Samsung Galaxy S24 Ultra", Description = "Titanium Gray =", Price = 57999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/2.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 2, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 3, CategoryId = 1, Name = "Google Pixel 8 Pro", Description = "Obsidian =", Price = 39999m, OldPrice = 42999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/3.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 3, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 4, CategoryId = 1, Name = "Xiaomi 14 Ultra", Description = "Black =", Price = 54999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/4.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 5, CategoryId = 1, Name = "OnePlus 12", Description = "Silky Black =", Price = 34999m, OldPrice = 37999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/5.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 6, CategoryId = 1, Name = "iPhone 14 128GB", Description = "Blue =", Price = 29999m, OldPrice = 32999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/6.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 6, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 7, CategoryId = 1, Name = "Samsung Galaxy A54 5G", Description = "Awesome Graphite =", Price = 14999m, OldPrice = 16999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/7.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 7, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 8, CategoryId = 1, Name = "Google Pixel 7a", Description = "Sea =", Price = 18999m, OldPrice = 20999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/8.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 8, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 9, CategoryId = 1, Name = "Xiaomi Redmi Note 13 Pro", Description = "Midnight Black =", Price = 12999m, OldPrice = 14999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/9.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 9, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 10, CategoryId = 1, Name = "Sony Xperia 1 V", Description = "Black =", Price = 48999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/10.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 11, CategoryId = 1, Name = "Motorola Edge 40", Description = "Eclipse Black =", Price = 15999m, OldPrice = 17999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/11.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 11, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 12, CategoryId = 1, Name = "ASUS Zenfone 10", Description = "Midnight Black =", Price = 28999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/12.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 13, CategoryId = 1, Name = "Nothing Phone (2)", Description = "Dark Grey =", Price = 24999m, OldPrice = 27999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/13.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 13, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 14, CategoryId = 1, Name = "iPhone 15 Plus 256GB", Description = "Blue =", Price = 45999m, OldPrice = 49999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/14.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 14, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 15, CategoryId = 1, Name = "Samsung Galaxy S23 FE", Description = "Graphite =", Price = 21999m, OldPrice = 24999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/15.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 16, CategoryId = 1, Name = "Huawei P60 Pro", Description = "Rococo Pearl =", Price = 36999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/16.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 16, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 17, CategoryId = 1, Name = "Oppo Find X6 Pro", Description = "Brown Leather =", Price = 38999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/17.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 17, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 18, CategoryId = 1, Name = "Vivo X100 Pro", Description = "Asteroid Black =", Price = 41999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/18.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 18, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 19, CategoryId = 1, Name = "Realme GT 5", Description = "Silver =", Price = 22999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/19.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 19, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 20, CategoryId = 1, Name = "Poco F5 Pro", Description = "White =", Price = 18999m, OldPrice = 20999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/20.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, DateTimeKind.Utc) },
            
            // Cat 2: Ноутбуки (21-40)
            new Product { Id = 21, CategoryId = 2, Name = "MacBook Air M3 13\"", Description = "Midnight =", Price = 62999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/21.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 21, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 22, CategoryId = 2, Name = "MacBook Pro 14\" M3 Pro", Description = "Space Black =", Price = 104999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/22.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 23, CategoryId = 2, Name = "Dell XPS 13 9315", Description = "Sky =", Price = 48999m, OldPrice = 53999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/23.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 23, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 24, CategoryId = 2, Name = "HP Spectre x360 14", Description = "Nightfall Black =", Price = 59999m, OldPrice = 64999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/24.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 24, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 25, CategoryId = 2, Name = "Lenovo Yoga 9i Gen 8", Description = "Oatmeal =", Price = 67999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/25.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 26, CategoryId = 2, Name = "ASUS ROG Zephyrus G14", Description = "Eclipse Gray =", Price = 74999m, OldPrice = 79999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/26.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 26, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 27, CategoryId = 2, Name = "Razer Blade 15", Description = "Mercury =", Price = 119999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/27.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 27, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 28, CategoryId = 2, Name = "Acer Swift Edge 16", Description = "Olivine Black =", Price = 44999m, OldPrice = 49999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/28.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 28, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 29, CategoryId = 2, Name = "Microsoft Surface Laptop 5", Description = "Platinum =", Price = 38999m, OldPrice = 43999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/29.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 30, CategoryId = 2, Name = "LG Gram 17 2023", Description = "Obsidian Black =", Price = 55999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/30.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 2, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 31, CategoryId = 2, Name = "MSI Stealth 14 Studio", Description = "Star Blue =", Price = 69999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/31.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 3, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 32, CategoryId = 2, Name = "Lenovo Legion Pro 5i Gen 8", Description = "Onyx Grey =", Price = 72999m, OldPrice = 77999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/32.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 33, CategoryId = 2, Name = "HP Victus 16", Description = "Mica Silver =", Price = 36999m, OldPrice = 41999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/33.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 34, CategoryId = 2, Name = "ASUS Vivobook S 15 OLED", Description = "Cool Silver =", Price = 32999m, OldPrice = 37999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/34.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 6, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 35, CategoryId = 2, Name = "Gigabyte AERO 16 OLED", Description = "Silver =", Price = 89999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/35.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 7, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 36, CategoryId = 2, Name = "Samsung Galaxy Book 3 Ultra", Description = "Graphite =", Price = 110999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/36.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 8, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 37, CategoryId = 2, Name = "Framework Laptop 13", Description = "DIY Edition =", Price = 42999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/37.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 9, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 38, CategoryId = 2, Name = "Alienware m16 R1", Description = "Dark Metallic Moon =", Price = 125999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/38.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 39, CategoryId = 2, Name = "Acer Nitro 5 AN515", Description = "Black =", Price = 29999m, OldPrice = 34999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/39.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 11, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 40, CategoryId = 2, Name = "MacBook Pro 16\" M3 Max", Description = "Space Black =", Price = 162999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/40.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, DateTimeKind.Utc) },

            // Cat 3: Клавіатури та мишки (41-60)
            new Product { Id = 41, CategoryId = 3, Name = "Keychron K2 V2", Description = "Mechanical Keyboard =", Price = 4299m, OldPrice = 4799m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/41.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 13, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 42, CategoryId = 3, Name = "Logitech G502 Hero", Description = "Gaming Mouse =", Price = 2599m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/42.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 14, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 43, CategoryId = 3, Name = "Razer DeathAdder V3 Pro", Description = "Ultra-lightweight Wireless =", Price = 6299m, OldPrice = 6799m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/43.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 44, CategoryId = 3, Name = "SteelSeries Apex Pro TKL", Description = "OmniPoint Switches =", Price = 7999m, OldPrice = 8499m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/44.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 16, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 45, CategoryId = 3, Name = "Corsair K70 RGB MK.2", Description = "Cherry MX Speed =", Price = 5499m, OldPrice = 5999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/45.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 17, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 46, CategoryId = 3, Name = "Logitech MX Master 3S", Description = "Ergonomic Productivity =", Price = 4199m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/46.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 18, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 47, CategoryId = 3, Name = "Razer BlackWidow V4 Pro", Description = "Mechanical Gaming =", Price = 8999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/47.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 19, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 48, CategoryId = 3, Name = "Anne Pro 2 60%", Description = "Gateron Brown =", Price = 3599m, OldPrice = 4099m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/48.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 49, CategoryId = 3, Name = "Ducky One 3 TKL", Description = "Daybreak Case =", Price = 4499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/49.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 21, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 50, CategoryId = 3, Name = "Glorious Model O Wireless", Description = "Matte Black =", Price = 3299m, OldPrice = 3799m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/50.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 51, CategoryId = 3, Name = "Zowie EC2-C", Description = "Ergonomic Esports =", Price = 2899m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/51.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 23, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 52, CategoryId = 3, Name = "ASUS ROG Azoth", Description = "75% Wireless Custom =", Price = 10499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/52.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 24, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 53, CategoryId = 3, Name = "Logitech G Pro X Superlight 2", Description = "Magenta =", Price = 6999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/53.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 54, CategoryId = 3, Name = "HyperX Alloy Origins", Description = "Compact Mechanical =", Price = 3299m, OldPrice = 3799m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/54.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 26, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 55, CategoryId = 3, Name = "Wooting 60HE", Description = "Analog Mechanical =", Price = 7999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/55.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 27, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 56, CategoryId = 3, Name = "NuPhy Air75", Description = "Low Profile Wireless =", Price = 4899m, OldPrice = 5399m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/56.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 28, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 57, CategoryId = 3, Name = "Varmilo VA87M Moonlight", Description = "Cherry Quiet Red =", Price = 5299m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/57.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 58, CategoryId = 3, Name = "Microsoft Ergonomic Keyboard", Description = "Wired Split =", Price = 2199m, OldPrice = 2699m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/58.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 2, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 59, CategoryId = 3, Name = "Apple Magic Mouse", Description = "White =", Price = 3499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/59.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 3, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 60, CategoryId = 3, Name = "Logitech G915 TKL White", Description = "Lightspeed Wireless =", Price = 7999m, OldPrice = 8499m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/60.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, DateTimeKind.Utc) },

            // Cat 4: Навушники та аудіо (61-80)
            new Product { Id = 61, CategoryId = 4, Name = "Sony WH-1000XM5 Black", Description = "Wireless Noise Cancelling =", Price = 15999m, OldPrice = 17499m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/61.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 62, CategoryId = 4, Name = "Apple AirPods Pro 2", Description = "Active Noise Cancellation =", Price = 9999m, OldPrice = 10999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/62.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 6, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 63, CategoryId = 4, Name = "Bose QuietComfort Ultra", Description = "Immersive Audio =", Price = 14999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/63.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 7, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 64, CategoryId = 4, Name = "Sennheiser Momentum 4", Description = "Wireless =", Price = 12999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/64.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 8, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 65, CategoryId = 4, Name = "Apple AirPods Max", Description = "Space Grey =", Price = 23999m, OldPrice = 25999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/65.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 9, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 66, CategoryId = 4, Name = "Jabra Elite 10", Description = "Titanium Black =", Price = 8999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/66.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 67, CategoryId = 4, Name = "JBL Flip 6 Blue", Description = "Portable Waterproof =", Price = 4499m, OldPrice = 4999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/67.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 11, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 68, CategoryId = 4, Name = "Marshall Major IV Black", Description = "Wireless =", Price = 5299m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/68.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 69, CategoryId = 4, Name = "Beats Studio Pro", Description = "Navy =", Price = 12499m, OldPrice = 13999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/69.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 13, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 70, CategoryId = 4, Name = "Nothing Ear (2)", Description = "Transparent =", Price = 5499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/70.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 14, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 71, CategoryId = 4, Name = "Audio-Technica ATH-M50xBT2", Description = "Professional Studio =", Price = 7899m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/71.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 72, CategoryId = 4, Name = "Beyerdynamic DT 770 Pro 80 Ohm", Description = "Studio Reference =", Price = 5999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/72.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 16, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 73, CategoryId = 4, Name = "SteelSeries Arctis Nova Pro", Description = "Wireless Gaming =", Price = 14999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/73.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 17, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 74, CategoryId = 4, Name = "Razer BlackShark V2 Pro 2023", Description = "Esports Grade =", Price = 7999m, OldPrice = 8499m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/74.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 18, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 75, CategoryId = 4, Name = "Logitech G Pro X 2 LIGHTSPEED", Description = "Graphene Gaming =", Price = 10499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/75.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 19, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 76, CategoryId = 4, Name = "HyperX Cloud III Wireless", Description = "Black =", Price = 6499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/76.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 77, CategoryId = 4, Name = "Sonos Era 100 Black", Description = "Smart Speaker =", Price = 11999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/77.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 21, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 78, CategoryId = 4, Name = "Bang & Olufsen Beosound A1", Description = "Gen 2 Waterproof =", Price = 10999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/78.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 79, CategoryId = 4, Name = "Shure SM7B", Description = "Dynamic Vocal =", Price = 16999m, OldPrice = 18499m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/79.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 23, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 80, CategoryId = 4, Name = "Blue Yeti Blackout", Description = "USB Streaming =", Price = 5499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/80.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 24, 0, 0, 0, DateTimeKind.Utc) },
            
            // Cat 5: Комплектуючі (81-100)
            new Product { Id = 81, CategoryId = 5, Name = "NVIDIA RTX 5090 24GB", Description = "ROG Strix OC Edition =", Price = 94999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/81.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 82, CategoryId = 5, Name = "NVIDIA RTX 5080 16GB", Description = "MSI Gaming X Slim =", Price = 68999m, OldPrice = 73999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/82.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 26, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 83, CategoryId = 5, Name = "NVIDIA RTX 4070 Ti 12GB", Description = "ASUS TUF Gaming =", Price = 38999m, OldPrice = 43999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/83.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 27, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 84, CategoryId = 5, Name = "AMD Radeon RX 7900 XTX", Description = "PowerColor Red Devil =", Price = 48999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/84.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 28, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 85, CategoryId = 5, Name = "Intel Core i9-14900K", Description = "24 Cores =", Price = 26999m, OldPrice = 31999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/85.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 86, CategoryId = 5, Name = "Intel Core i5-13600K", Description = "14 Cores Performance =", Price = 13499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/86.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 2, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 87, CategoryId = 5, Name = "AMD Ryzen 9 7950X3D", Description = "16 Cores Gaming =", Price = 27999m, OldPrice = 32999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/87.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 3, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 88, CategoryId = 5, Name = "AMD Ryzen 7 7800X3D", Description = "Ultimate Gaming CPU =", Price = 16999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/88.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 89, CategoryId = 5, Name = "Samsung 990 Pro 2TB", Description = "NVMe Gen4 SSD with Heatsink =", Price = 7499m, OldPrice = 7999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/89.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 90, CategoryId = 5, Name = "Corsair Vengeance 32GB DDR5", Description = "600MHz RGB =", Price = 5499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/90.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 6, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 91, CategoryId = 5, Name = "ASUS ROG Maximus Z790 Hero", Description = "LGA1700 Flagship =", Price = 24999m, OldPrice = 29999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/91.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 7, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 92, CategoryId = 5, Name = "MSI MAG B650 Tomahawk WiFi", Description = "AM5 Performance =", Price = 8999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/92.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 8, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 93, CategoryId = 5, Name = "Noctua NH-D15 chromax.black", Description = "Premium Dual-Tower =", Price = 4899m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/93.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 9, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 94, CategoryId = 5, Name = "NZXT Kraken Elite 360", Description = "RGB AIO Liquid Cooler with LCD =", Price = 12499m, OldPrice = 13999m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/94.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 95, CategoryId = 5, Name = "Seasonic Focus GX-850", Description = "850W Gold Full Modular =", Price = 5999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/95.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 11, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 96, CategoryId = 5, Name = "Lian Li PC-O11 Dynamic EVO", Description = "Black Tempered Glass =", Price = 6899m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/96.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 97, CategoryId = 5, Name = "WD Black SN850X 1TB", Description = "High Performance Gen4 =", Price = 4299m, OldPrice = 4799m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/97.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 13, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 98, CategoryId = 5, Name = "Crucial P5 Plus 2TB", Description = "PCIe Gen4 NVMe SSD =", Price = 5999m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/98.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 14, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 99, CategoryId = 5, Name = "G.Skill Trident Z5 RGB 64GB", Description = "6400MHz DDR5 =", Price = 9899m, OldPrice = 10899m, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/99.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, DateTimeKind.Utc) },
            new Product { Id = 100, CategoryId = 5, Name = "EVGA SuperNOVA 1000 G7", Description = "1000W Gold Compact =", Price = 8499m, OldPrice = null, ImageUrl = "https://res.cloudinary.com/dvtgcc1cl/image/upload/v1/shop/products/100.png", StockQuantity = 15, CreatedAt = new DateTime(2024, 3, 16, 0, 0, 0, DateTimeKind.Utc) }
        );
    }
}
