// <auto-generated />
using System;
using Exam2.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302183922_AddUserImageUrl")]
    partial class AddUserImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Exam2.Backend.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400",
                            Name = "Електроніка"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400",
                            Name = "Одяг"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
                            Name = "Дім та сад"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1461896836934- voices-3?w=400",
                            Name = "Спорт"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400",
                            Name = "Книги"
                        });
                });

            modelBuilder.Entity("Exam2.Backend.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6.4\" Super AMOLED, 128GB, 5G",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
                            Name = "Смартфон Samsung Galaxy A54",
                            OldPrice = 15999m,
                            Price = 13999m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15.6\" FHD, Intel i5, 16GB RAM, 512GB SSD",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
                            Name = "Ноутбук ASUS VivoBook 15",
                            Price = 25999m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Бездротові, шумопоглинання",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
                            Name = "Навушники Sony WH-1000XM5",
                            OldPrice = 13999m,
                            Price = 11499m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Водонепроникна, розміри M-XXL",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
                            Name = "Куртка зимова чоловіча",
                            OldPrice = 4299m,
                            Price = 3499m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Унісекс, всі розміри",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
                            Name = "Кросівки Nike Air Max",
                            Price = 4999m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "12 предметів, сталь",
                            ImageUrl = "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
                            Name = "Набір садових інструментів",
                            OldPrice = 1599m,
                            Price = 1299m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10W, димер, USB зарядка",
                            ImageUrl = "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400",
                            Name = "LED лампа настільна",
                            Price = 799m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Гумове покриття, хромована ручка",
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
                            Name = "Гантелі 2x10 кг",
                            OldPrice = 2199m,
                            Price = 1899m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "183x61см, 6мм товщина",
                            ImageUrl = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
                            Name = "Yoga мат професійний",
                            Price = 699m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Подарункове видання, тверда обкладинка",
                            ImageUrl = "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400",
                            Name = "Кобзар - Тарас Шевченко",
                            OldPrice = 550m,
                            Price = 450m,
                            StockQuantity = 80
                        });
                });

            modelBuilder.Entity("Exam2.Backend.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.OrderItem", b =>
                {
                    b.HasOne("Exam2.Backend.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exam2.Backend.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.Product", b =>
                {
                    b.HasOne("Exam2.Backend.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.ProductDetail", b =>
                {
                    b.HasOne("Exam2.Backend.Entities.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Exam2.Backend.Entities.Product", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
